name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag leakingmemory/alpine-casablanca:build
    - name: Build the runtime Docker image
      run: docker build . --target casablanca-runtime --file Dockerfile --tag leakingmemory/alpine-casablanca:runtime
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Push to Docker Hub build image
      run: docker push leakingmemory/alpine-casablanca:build
    - name: Push to Docker Hub runtime image
      run: docker push leakingmemory/alpine-casablanca:runtime
